# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Card(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, card_number: str=None):  # noqa: E501
        """Card - a model defined in Swagger

        :param card_number: The card_number of this Card.  # noqa: E501
        :type card_number: str
        """
        self.swagger_types = {
            'card_number': str
        }

        self.attribute_map = {
            'card_number': 'cardNumber'
        }

        self._card_number = card_number

    @classmethod
    def from_dict(cls, dikt) -> 'Card':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Card of this Card.  # noqa: E501
        :rtype: Card
        """
        return util.deserialize_model(dikt, cls)

    @property
    def card_number(self) -> str:
        """Gets the card_number of this Card.


        :return: The card_number of this Card.
        :rtype: str
        """
        return self._card_number

    @card_number.setter
    def card_number(self, card_number: str):
        """Sets the card_number of this Card.


        :param card_number: The card_number of this Card.
        :type card_number: str
        """

        self._card_number = card_number
