---
swagger: "2.0"
info:
  description: "This is a simple cardreader server."
  version: "1.0.0"
  title: "Cardreader API"
  termsOfService: "https://www.gk-software.com/terms/"
  contact:
    email: "snoerenberg@gk-software.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/v1"
tags:
- name: "cardreader"
  description: "Access to RS485 card reader"
  externalDocs:
    description: "RS485"
    url: "https://shop.in-circuit.de/product_info.php?products_id=81"
paths:
  /cardreader/getCardNumber:
    get:
      tags:
      - "cardreader"
      summary: "Get cardnumber from serial reader"
      description: "Serial connection is initialized for 10 seconds and is awaiting\
        \ a card to be present"
      operationId: "cardreader_get_card_number_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Card"
        404:
          description: "no card found"
      x-swagger-router-controller: "swagger_server.controllers.cardreader_controller"
definitions:
  Card:
    type: "object"
    properties:
      cardNumber:
        type: "string"
    example:
      cardNumber: "cardNumber"
